config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include("django.conf.urls.i18n"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', include("web.urls"))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.urls import path,include
from .views import about_company_page,our_factory_page,our_products_page,contact_page,currency_page,CreateApply
# app_name='lang'


urlpatterns = [
    path('', about_company_page, name='about_company_page_url'),
    path('our_factory/', our_factory_page, name='our_factory_page_url'),
    path('our_product/', our_products_page, name='our_products_page_url'),
    # path('contact/', contact_page, name='contact_page_url'),
    path('currency/', currency_page, name='currency_page_url'),
    path('create_apply/', CreateApply.as_view(), name='create_apply_url'),
]

web/models.py
from django.db import models
from parler.models import TranslatableModel, TranslatedFields


# Create your models here.

class Currency(models.Model):
    code = models.CharField(max_length=3)
    value = models.FloatField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code


class Apply(TranslatableModel):
    translations = TranslatedFields(
        full_name=models.CharField(max_length=50),
        email=models.CharField(max_length=30),
        text=models.TextField(max_length=1000),
    )

    def __str__(self):
        return self.email


class News(TranslatableModel):
    translations = TranslatedFields(
        topic=models.CharField(max_length=80),
        image=models.ImageField(upload_to='image/'),
        description=models.TextField(max_length=1000),
        create_at=models.DateTimeField(auto_now_add=True)
    )

    def __str__(self):
        return self.topic

web/forms.py
from django import forms
from .models import Apply


class ApplyForm(forms.ModelForm):
    email = forms.EmailField(error_messages={"invalid": "Iltimos, to'g'ri elektron manzilni kiriting."})

    class Meta:
        model = Apply
        fields = '__all__'

web/views.py
from itertools import chain

from django.core.validators import validate_email
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from django.db.models import Q
from django.shortcuts import render
import currencyapicom
import requests
from prompt_toolkit.validation import ValidationError

from .forms import ApplyForm
from .models import Currency, Apply, News

# USD = Currency.objects.filter(code="USD")
# RUB = Currency.objects.filter(code="RUB")
# EUR = Currency.objects.filter(code="EUR")
# UZS = Currency.objects.filter(code="UZS")
# all_currency = Currency.objects.exclude(Q(code="USD") | Q(code="RUB") | Q(code="EUR") | Q(code="UZS"))
# currency = list(chain(USD, EUR, RUB, UZS))
# print(currency)
# UZS = Currency.objects.filter(code="UZS").first()
# context = {"currency": currency, "UZS": UZS}


# Create your views here.


def about_company_page(request):
    RUB = Currency.objects.filter(code="RUB")
    EUR = Currency.objects.filter(code="EUR")
    UZS = Currency.objects.filter(code="UZS")
    currency = list(chain(EUR, RUB, UZS))
    UZS = Currency.objects.filter(code="UZS").first()
    context = {"currency": currency, "UZS": UZS}
    return render(request, "web/about_company.html", context)


def our_factory_page(request):
    RUB = Currency.objects.filter(code="RUB")
    EUR = Currency.objects.filter(code="EUR")
    UZS = Currency.objects.filter(code="UZS")
    currency = list(chain(EUR, RUB, UZS))
    UZS = Currency.objects.filter(code="UZS").first()
    context = {"currency": currency, "UZS": UZS}

    return render(request, "web/our_factory.html", context)


def our_products_page(request):
    RUB = Currency.objects.filter(code="RUB")
    EUR = Currency.objects.filter(code="EUR")
    UZS = Currency.objects.filter(code="UZS")
    currency = list(chain(EUR, RUB, UZS))
    UZS = Currency.objects.filter(code="UZS").first()
    context = {"currency": currency, "UZS": UZS}
    news = News.objects.all()
    context['news'] = news
    return render(request, "web/our_products.html", context)


def contact_page(request):
    RUB = Currency.objects.filter(code="RUB")
    EUR = Currency.objects.filter(code="EUR")
    UZS = Currency.objects.filter(code="UZS")
    currency = list(chain(EUR, RUB, UZS))
    UZS = Currency.objects.filter(code="UZS").first()
    context = {"currency": currency, "UZS": UZS}
    return render(request, "web/contact.html", context)


def currency_page(request):
    RUB = Currency.objects.filter(code="RUB")
    EUR = Currency.objects.filter(code="EUR")
    UZS = Currency.objects.filter(code="UZS")
    currency = list(chain(EUR, RUB, UZS))
    UZS = Currency.objects.filter(code="UZS").first()
    context = {"currency": currency, "UZS": UZS}
    return render(request, "web/currency.html", context)


def currencyapi():
    client = currencyapicom.Client('xc9TTNtkKFgqrWJy1uiZl630LyQnt80cpopjVBJE')
    data = client.latest()


class CreateApply(CreateView):
    model = Apply
    form_class = ApplyForm
    template_name = 'web/contact.html'
    success_url = '/'

    def form_valid(self, form):
        # Modelni saqlash uchun ishlatiladi
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <title>Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!-- Swiper css -->
    <link rel="stylesheet" href="{% static 'assets/css/swiper-bundle.min.css' %}">


    <link href="{% static 'assets_slove/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets_slove/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets_slove/css/templatemo-574-mexant.css' %}">
    <link rel="stylesheet" href="{% static 'assets_slove/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets_slove/css/animate.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'news/style.css' %}">

    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pontano+Sans:wght@700&display=swap" rel="stylesheet">


</head>
<body style="overflow: scroll !important;">

<!-- Start Top Nav -->
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
    <div class="container text-light">
        <div class="w-100 d-flex justify-content-between">
            <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
            </div>
            <div>
                <a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i
                        class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.instagram.com/" target="_blank"><i
                        class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://twitter.com/" target="_blank"><i
                        class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i
                        class="fab fa-linkedin fa-sm fa-fw"></i></a>
            </div>
        </div>
    </div>
</nav>
<!-- Close Top Nav -->


<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">

        <a id="kxorazmtext" class="navbar-brand text-success logo h1 align-self-center"
           href="#">
            KXorezmTex
        </a>

        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between"
             id="templatemo_main_nav">
            <div class="flex-fill">
                <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about_company_page_url' %}"><b>{% trans "About Company" %}</b>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'our_factory_page_url' %}"><b>{% trans "Our Factory" %}</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'our_products_page_url' %}"><b>{% trans "Our products" %}</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_apply_url' %}"><b>{% trans "Contact" %}</b></a>
                    </li>
                </ul>
            </div>
            <div class="flag_container">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}

                <ul class="flag_menu">
                    <li><a href="/en/"><img width="16px" height="16px" src="{% static "assets/img/flag/us.svg" %}"
                                            alt=""></a>
                    </li>
                    <li><a href="/ru/"><img width="16px" height="16px" src="{% static "assets/img/flag/ru.svg" %}"
                                            alt=""></a>
                    </li>
                    <li><a href="/uz/"><img width="16px" height="16px" src="{% static "assets/img/flag/uz.svg" %}"
                                            alt=""></a>
                    </li>
                </ul>


            </div>

        </div>

    </div>
</nav>
<!-- Close Header -->





{% block content %}


{% endblock content %}



<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
    <div class="container">


        <div class="row">

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-success border-bottom pb-3 border-light logo" style="color: gold !important;">
                    KXorezmTex</h2>
                <ul style="text-align: left !important;" class="list-unstyled text-light footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        123 Consectetur at ligula 10660
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Currency</h2>
                    <ul  style="text-align: left !important;" class="list-unstyled text-light footer-link-list">
                       {% for money in currency %}
                             <li>1USD = {{ money.value }} {{ money.code }}</li>
                       {% endfor %}



                    </ul>
                </div>

            {#            <div class="col-md-4 pt-5">#}
            {#                <h2 class="h2 text-light border-bottom pb-3 border-light">Exchange rates</h2>#}
            {#                <button id="myBtn" type="button" class="btn btn-primary">Primary</button>#}
            {#                <script>#}
            {#                    document.getElementById("myBtn").onclick = displayDate;#}
            {##}
            {#                    function displayDate() {#}
            {#                        console.log("salom")#}
            {#                    }#}
            {#                </script>#}
            {##}
            {##}
            {#            </div>#}


        </div>

        <div class="row text-light mb-4">
            <div class="col-12 mb-3">
                <div class="w-100 my-3 border-top border-light"></div>
            </div>
            <div class="col-auto me-auto">
                <ul class="list-inline text-left footer-icons">
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i
                                class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i
                                class="fab fa-instagram fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i
                                class="fab fa-twitter fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i
                                class="fab fa-linkedin fa-lg fa-fw"></i></a>
                    </li>
                </ul>
            </div>

        </div>
    </div>

    <div class="w-100 bg-black py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-left text-light">
                        Copyright &copy; 2021 Company Name
                        | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

</footer>
<!-- End Footer -->

<!-- Start Script -->
<script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>
<!-- Start Script -->
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'assets/js/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/templatemo.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<!-- End Script -->


<script src="{% static 'assets_slove/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets_slove/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'assets_slove/js/isotope.min.js' %}"></script>
<script src="{% static 'assets_slove/js/owl-carousel.js' %}"></script>

<script src="{% static 'assets_slove/js/tabs.js' %}"></script>
<script src="{% static 'assets_slove/js/swiper.js' %}"></script>
<script src="{% static 'assets_slove/js/custom.js' %}"></script>


<!-- news  -->
<script src="{% static 'news/index.js' %}"></script>


<!-- Bootstrap -->
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>#}
</body>
</html>

web/templates/web/contact.html
{% extends "base.html" %}
{% load static %}




{% block content %}
    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
        </div>
    </div>
    <section1 class="contact_1">
        <div class="container_1">
            <div class="content_1">
                <div class="left-side_1">
                    <div class="address_1 details_1">
                        <i class="fas fa-map-marked-alt"></i>
                        <div class="topic_1">Adrress</div>
                        <div class="text-one_1">Surhet</div>
                        <div class="text-two_1">Surhen ,NP12</div>
                        <div class="text-two_1">Brindrangare 06</div>
                    </div>
                    <div class="phone_1 details_1">
                        <i class="fas fa-phone-alt"></i>
                        <div class="topic_1">Phone</div>
                        <div class="text-one_1">+99 899 966 10 84</div>
                        <div class="text-two_1">+99 899 966 10 84</div>

                    </div>
                    <div class="Email_1 details_1">
                        <i class="fas fa-envelope"></i>
                        <div class="text-one_1">muhammadibragimov439@gmail.com</div>
                        <div class="text-two_1">info.codinglab</div>

                    </div>
                </div>

                <div class="right-side_1">
                    <div class="topic-text_1">Send massage</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur cumque explicabo nulla?
                        Consequuntur, deserunt dolores, libero nesciunt nobis repellendus sequi, soluta sunt tempora
                        totam veritatis!</p>

                    <form method="post">
                        {% csrf_token %}
                        <div class="input-box_1">
                            <input id="id_full_name" name="full_name" type="text" placeholder="Enter your name">
                        </div>
                        <div class="input-box_1">
                            <input id="id_email" name="email" type="text" placeholder="Enter your email">
                        </div>
                        <div class="input-box_1 massage-box_1">
                            <textarea id="id_text" name="text"></textarea>
                        </div>
                        <div class="button_1">
                            <button type="submit" class="btn btn-outline-primary">Send Now</button>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                <strong>Error:</strong> Please correct the errors below.
                                <ul>
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ field.label }}: {{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </form>
                </div>

            </div>
        </div>
    </section1>



    <!-- Start Map -->
    <div id="mapid" style="width: 100%; height: 300px;">
        <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d3422651.0953391436!2d63.70991626637057!3d41.03914710472569!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sKxorazmTex!5e1!3m2!1suz!2s!4v1682917708469!5m2!1suz!2s"
                width="600" height="450" style="border:0; width: 100%" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <!-- Start Contact -->
    <div class="container py-5">
        <div class="row py-5">

        </div>
    </div>
    <!-- End Contact -->




{% endblock %}

web/templates/web/currency.html
{% extends 'base.html' %}
{%  load i18n %}
{% load static %}


{% block content %}
 <section2 class="container py-5">
        <div class="row text-center pt-5 pb-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1"><b>Currency</b></h1>
            </div>
        </div>
        <div class="row">
            {% for data in currency %}
                  <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"></div>
                    <h2 class="h5 mt-4 text-center">1USD = {{ data.value|floatformat }} {{ data.code }} </h2>
                </div>
            </div>
            {% endfor %}




        </div>
    </section2>
{% endblock %}